name: Codespell

on:
  pull_request:
    branches: [main, devel]

defaults:
  run:
    shell: bash

jobs:
  codespell:
    name: codespell (typos)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: codespell
